// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.RegexTester
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("pattern")]
        public string Pattern { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("flags")]
        public string Flags { get; set; }

        [JsonProperty("test_type")]
        public string TestType { get; set; }

        [JsonProperty("replacement")]
        public object Replacement { get; set; }

        [JsonProperty("is_valid_regex")]
        public bool IsValidRegex { get; set; }

        [JsonProperty("regex_info")]
        public RegexInfo RegexInfo { get; set; }

        [JsonProperty("test_results")]
        public TestResults TestResults { get; set; }

        [JsonProperty("performance")]
        public Performance Performance { get; set; }

        [JsonProperty("pattern_analysis")]
        public PatternAnalysis PatternAnalysis { get; set; }

        [JsonProperty("suggestions")]
        public string[] Suggestions { get; set; }

        [JsonProperty("common_patterns")]
        public CommonPattern[] CommonPatterns { get; set; }

        [JsonProperty("regex_guide")]
        public RegexGuide RegexGuide { get; set; }
    }

    public partial class CommonPattern
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("pattern")]
        public string Pattern { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("example")]
        public string Example { get; set; }
    }

    public partial class PatternAnalysis
    {
        [JsonProperty("contains_anchors")]
        public ContainsAnchors ContainsAnchors { get; set; }

        [JsonProperty("contains_quantifiers")]
        public ContainsQuantifiers ContainsQuantifiers { get; set; }

        [JsonProperty("contains_groups")]
        public ContainsGroups ContainsGroups { get; set; }

        [JsonProperty("contains_character_classes")]
        public ContainsCharacterClasses ContainsCharacterClasses { get; set; }

        [JsonProperty("contains_special_chars")]
        public ContainsSpecialChars ContainsSpecialChars { get; set; }
    }

    public partial class ContainsAnchors
    {
        [JsonProperty("start_anchor")]
        public bool StartAnchor { get; set; }

        [JsonProperty("end_anchor")]
        public bool EndAnchor { get; set; }

        [JsonProperty("word_boundary")]
        public bool WordBoundary { get; set; }
    }

    public partial class ContainsCharacterClasses
    {
        [JsonProperty("predefined_classes")]
        public bool PredefinedClasses { get; set; }

        [JsonProperty("custom_classes")]
        public bool CustomClasses { get; set; }

        [JsonProperty("negated_classes")]
        public bool NegatedClasses { get; set; }
    }

    public partial class ContainsGroups
    {
        [JsonProperty("capturing_groups")]
        public long CapturingGroups { get; set; }

        [JsonProperty("non_capturing_groups")]
        public long NonCapturingGroups { get; set; }

        [JsonProperty("named_groups")]
        public long NamedGroups { get; set; }
    }

    public partial class ContainsQuantifiers
    {
        [JsonProperty("zero_or_more")]
        public bool ZeroOrMore { get; set; }

        [JsonProperty("one_or_more")]
        public bool OneOrMore { get; set; }

        [JsonProperty("zero_or_one")]
        public bool ZeroOrOne { get; set; }

        [JsonProperty("specific_count")]
        public bool SpecificCount { get; set; }

        [JsonProperty("range_count")]
        public bool RangeCount { get; set; }
    }

    public partial class ContainsSpecialChars
    {
        [JsonProperty("wildcard")]
        public bool Wildcard { get; set; }

        [JsonProperty("pipe")]
        public bool Pipe { get; set; }

        [JsonProperty("escape_sequences")]
        public long EscapeSequences { get; set; }
    }

    public partial class Performance
    {
        [JsonProperty("iterations")]
        public long Iterations { get; set; }

        [JsonProperty("total_time_ms")]
        public long TotalTimeMs { get; set; }

        [JsonProperty("average_time_ms")]
        public long AverageTimeMs { get; set; }

        [JsonProperty("performance_rating")]
        public string PerformanceRating { get; set; }
    }

    public partial class RegexGuide
    {
        [JsonProperty("basic_syntax")]
        public BasicSyntax[] BasicSyntax { get; set; }

        [JsonProperty("character_classes")]
        public BasicSyntax[] CharacterClasses { get; set; }

        [JsonProperty("quantifiers")]
        public BasicSyntax[] Quantifiers { get; set; }

        [JsonProperty("groups")]
        public BasicSyntax[] Groups { get; set; }

        [JsonProperty("flags")]
        public Flag[] Flags { get; set; }
    }

    public partial class BasicSyntax
    {
        [JsonProperty("symbol")]
        public string Symbol { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }
    }

    public partial class Flag
    {
        [JsonProperty("flag")]
        public string FlagFlag { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }
    }

    public partial class RegexInfo
    {
        [JsonProperty("pattern")]
        public string Pattern { get; set; }

        [JsonProperty("flags")]
        public Flags Flags { get; set; }

        [JsonProperty("source")]
        public string Source { get; set; }

        [JsonProperty("last_index")]
        public long LastIndex { get; set; }

        [JsonProperty("pattern_length")]
        public long PatternLength { get; set; }

        [JsonProperty("complexity")]
        public string Complexity { get; set; }
    }

    public partial class Flags
    {
        [JsonProperty("global")]
        public bool Global { get; set; }

        [JsonProperty("ignore_case")]
        public bool IgnoreCase { get; set; }

        [JsonProperty("multiline")]
        public bool Multiline { get; set; }

        [JsonProperty("sticky")]
        public bool Sticky { get; set; }

        [JsonProperty("unicode")]
        public bool Unicode { get; set; }

        [JsonProperty("dot_all")]
        public bool DotAll { get; set; }
    }

    public partial class TestResults
    {
        [JsonProperty("operation")]
        public string Operation { get; set; }

        [JsonProperty("result")]
        public bool Result { get; set; }

        [JsonProperty("execution_time_ms")]
        public long ExecutionTimeMs { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }
    }
}
